[build]
python_version = "3.11"
requirements = "requirements.txt"

[secrets]
huggingface-secret = "HF_TOKEN"

[gpu]
type = "H100"
count = 1

[timeout]
seconds = 300

[environment]
CUDA_VISIBLE_DEVICES = "0"
PYTORCH_CUDA_ALLOC_CONF = "max_split_size_mb:128"